// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TD.Data;

#nullable disable

namespace TD.Migrations
{
    [DbContext(typeof(TDDbContext))]
    [Migration("20260613171429_AddMemberEffortAndDriveOverride")]
    partial class AddMemberEffortAndDriveOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TD.Models.AgentMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Effort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentTeamId");

                    b.ToTable("AgentMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentTeamId = 1,
                            Effort = 2,
                            Model = 0,
                            Name = "The Quarterback",
                            Role = 0,
                            SystemPrompt = "You are the Quarterback (QB) — the lead planner and on-field leader of a software engineering team.\n\nIn the Huddle you plan with the Head Coach (the user): turn their idea into a clear, actionable\nplaybook the team can execute. Be conversational and collaborative — ask clarifying questions when\nthe request is ambiguous, propose concrete approaches with their trade-offs, and push back\nrespectfully on anything risky, over-complex, or under-scoped. Build on the conversation rather than\nrestarting each turn, and don't dump a full spec on the first message.\n\nWhen you and the Coach are aligned, summarize the agreed plan as a numbered playbook of discrete\ntasks that can each be handed to an individual teammate:\n\n## Playbook\n1. **[Task name]** — what to do, plus acceptance criteria\n2. **[Task name]** — what to do, plus acceptance criteria\n\nDo not finalize the playbook until the Coach confirms they're happy with it. Once the ball is\nsnapped you own the plan: delegate each assignment to the right player, respect dependencies between\ntasks, and coordinate the drive to completion. You make the final call."
                        },
                        new
                        {
                            Id = 2,
                            AgentTeamId = 1,
                            Effort = 2,
                            Model = 1,
                            Name = "Left Guard",
                            Role = 1,
                            SystemPrompt = "You are the Left Guard — a core implementer. You receive your assignment from the Quarterback and execute it with precision."
                        },
                        new
                        {
                            Id = 3,
                            AgentTeamId = 1,
                            Effort = 2,
                            Model = 1,
                            Name = "Right Guard",
                            Role = 1,
                            SystemPrompt = "You are the Right Guard — a parallel implementer. You work alongside the Left Guard on your assigned portion."
                        },
                        new
                        {
                            Id = 4,
                            AgentTeamId = 1,
                            Effort = 2,
                            Model = 1,
                            Name = "The Safety",
                            Role = 2,
                            SystemPrompt = "You are the Safety — the code reviewer. You review all output from the Guards before it merges."
                        },
                        new
                        {
                            Id = 5,
                            AgentTeamId = 1,
                            Effort = 1,
                            Model = 2,
                            Name = "The Scout",
                            Role = 3,
                            SystemPrompt = "You are the Scout — fast and lightweight. You write and run tests concurrently with implementation."
                        },
                        new
                        {
                            Id = 6,
                            AgentTeamId = 1,
                            Effort = 1,
                            Model = 2,
                            Name = "Special Teams",
                            Role = 4,
                            SystemPrompt = "You are Special Teams — handling CI/CD, infrastructure, and build pipeline work."
                        });
                });

            modelBuilder.Entity("TD.Models.AgentTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The default TD agent team.",
                            IsDefault = true,
                            Name = "The Playbook"
                        });
                });

            modelBuilder.Entity("TD.Models.CommunicationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Style")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentTeamId");

                    b.ToTable("CommunicationRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentTeamId = 1,
                            Description = "QB calls plays, Guards run parallel, Safety reviews before merge, Scout runs concurrently.",
                            Style = 1
                        });
                });

            modelBuilder.Entity("TD.Models.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Effort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HuddlePlan")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxParallelism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverrideTeamConfig")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkspaceMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentTeamId");

                    b.HasIndex("DriveId")
                        .IsUnique();

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("TD.Models.DriveLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DriveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveId");

                    b.ToTable("DriveLogs");
                });

            modelBuilder.Entity("TD.Models.DriveTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CostUsd")
                        .HasColumnType("REAL");

                    b.Property<int>("DriveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolsUsed")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveId", "Timestamp");

                    b.ToTable("DriveTurns");
                });

            modelBuilder.Entity("TD.Models.Play", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DriveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("DriveId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("TD.Models.AgentMember", b =>
                {
                    b.HasOne("TD.Models.AgentTeam", "AgentTeam")
                        .WithMany("Members")
                        .HasForeignKey("AgentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentTeam");
                });

            modelBuilder.Entity("TD.Models.CommunicationRule", b =>
                {
                    b.HasOne("TD.Models.AgentTeam", "AgentTeam")
                        .WithMany("CommunicationRules")
                        .HasForeignKey("AgentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentTeam");
                });

            modelBuilder.Entity("TD.Models.Drive", b =>
                {
                    b.HasOne("TD.Models.AgentTeam", "AgentTeam")
                        .WithMany()
                        .HasForeignKey("AgentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentTeam");
                });

            modelBuilder.Entity("TD.Models.DriveLog", b =>
                {
                    b.HasOne("TD.Models.Drive", "Drive")
                        .WithMany("Logs")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("TD.Models.DriveTurn", b =>
                {
                    b.HasOne("TD.Models.Drive", "Drive")
                        .WithMany("Turns")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("TD.Models.Play", b =>
                {
                    b.HasOne("TD.Models.AgentMember", "AssignedMember")
                        .WithMany()
                        .HasForeignKey("AssignedMemberId");

                    b.HasOne("TD.Models.Drive", "Drive")
                        .WithMany("Plays")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("TD.Models.AgentTeam", b =>
                {
                    b.Navigation("CommunicationRules");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TD.Models.Drive", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Plays");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
