/*
 * Cloud Nine — airy, ultra-light theme with soft indigo primary.
 * Background is a whisper of warm gray. Clean and modern feel.
 */

using MudBlazor;

namespace TD.Themes;

public static class CloudNineTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight()
        {
            TableHover = "rgba(0,0,0,0.03)",
            OverlayLight = "rgba(255,255,255,0.5)",
            OverlayDark = "rgba(33,33,33,0.5)",
            GrayDarker = "#616161",
            GrayDark = "#757575",
            GrayLighter = "#EEEEEE",
            GrayLight = "#BDBDBD",
            GrayDefault = "#9E9E9E",
            RippleOpacitySecondary = 0.18,
            RippleOpacity = 0.08,
            HoverOpacity = 0.04,
            Surface = "#ffffff",
            Background = "#fafafa",
            BackgroundGray = "#f4f4f5",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(189,189,189,1)",
            ActionDisabled = "rgba(0,0,0,0.26)",
            TextDisabled = "rgba(0,0,0,0.38)",
            TableStriped = "rgba(0,0,0,0.015)",
            LinesDefault = "rgba(0,0,0,0.09)",
            ActionDisabledBackground = "rgba(0,0,0,0.1)",
            TableLines = "rgba(238,238,238,1)",
            Divider = "rgba(238,238,238,1)",
            DividerLight = "rgba(0,0,0,0.05)",
            Error = "#E53935",
            Tertiary = "#9FA8DA",
            TertiaryLighten = "#C5CAE9",
            TertiaryDarken = "#5C6BC0",
            ActionDefault = "rgba(0,0,0,0.54)",
            DarkLighten = "rgb(85,85,85)",
            ErrorLighten = "#EF5350",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(40,40,40)",
            White = "#fff",
            SecondaryLighten = "#f5f5f5",
            WarningDarken = "#E65100",
            PrimaryContrastText = "#ffffff",
            TextPrimary = "#1A237E",
            TextSecondary = "#5C6BC0",
            TertiaryContrastText = "#ffffff",
            DarkContrastText = "#C5CAE9",
            Secondary = "#E8EAF6",
            DrawerIcon = "#5C6BC0",
            DrawerText = "#303F9F",
            Warning = "#FF9800",
            SecondaryDarken = "#C5CAE9",
            InfoDarken = "#01579B",
            SuccessDarken = "#1B5E20",
            Info = "#42A5F5",
            Success = "#66BB6A",
            Dark = "#1A237E",
            DrawerBackground = "#fbfbfc",
            WarningLighten = "#FFE0B2",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#303F9F",
            InfoContrastText = "#E3F2FD",
            InfoLighten = "#E3F2FD",
            SuccessContrastText = "#E8F5E9",
            SuccessLighten = "#E8F5E9",
            PrimaryLighten = "#7986CB",
            PrimaryDarken = "#283593",
            Primary = "#3F51B5",
            AppbarText = "#1A237E",
            AppbarBackground = "#fafafa",
            Black = "#000",
        },
        PaletteDark = new PaletteDark()
        {
            Surface = "rgba(45,45,55,1)",
            Background = "rgba(38,38,48,1)",
            BackgroundGray = "rgba(30,30,38,1)",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(255,255,255,0.28)",
            ActionDisabled = "rgba(255,255,255,0.26)",
            TextDisabled = "rgba(255,255,255,0.2)",
            TableStriped = "rgba(255,255,255,0.04)",
            LinesDefault = "rgba(255,255,255,0.1)",
            ActionDisabledBackground = "rgba(255,255,255,0.1)",
            TableLines = "rgba(255,255,255,0.1)",
            Divider = "rgba(255,255,255,0.1)",
            DividerLight = "rgba(255,255,255,0.05)",
            Error = "#EF5350",
            Tertiary = "#9FA8DA",
            TertiaryLighten = "#C5CAE9",
            TertiaryDarken = "#7986CB",
            ActionDefault = "rgba(159,168,218,1)",
            DarkLighten = "rgb(55,55,65)",
            ErrorLighten = "#EF9A9A",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(20,20,28)",
            White = "#fff",
            SecondaryLighten = "#5C6BC0",
            WarningDarken = "#FFB74D",
            PrimaryContrastText = "#E8EAF6",
            TextPrimary = "#E8EAF6",
            TextSecondary = "#C5CAE9",
            TertiaryContrastText = "#E8EAF6",
            DarkContrastText = "#E8EAF6",
            Secondary = "#303F9F",
            DrawerIcon = "#C5CAE9",
            DrawerText = "#E8EAF6",
            Warning = "#FFA726",
            SecondaryDarken = "#1A237E",
            InfoDarken = "#90CAF9",
            SuccessDarken = "#A5D6A7",
            Info = "#42A5F5",
            Success = "#66BB6A",
            Dark = "#1A237E",
            DrawerBackground = "#1a1a24",
            WarningLighten = "#3E2723",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#E8EAF6",
            InfoContrastText = "#0A1929",
            InfoLighten = "#0A1929",
            SuccessContrastText = "#0D2E16",
            SuccessLighten = "#0D2E16",
            PrimaryLighten = "#7986CB",
            PrimaryDarken = "#283593",
            Primary = "#5C6BC0",
            AppbarText = "#C5CAE9",
            AppbarBackground = "#161622",
            Black = "#000",
        },
        LayoutProperties = new LayoutProperties()
        {
            AppbarHeight = "64px",
            DefaultBorderRadius = "8px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
            DrawerWidthLeft = "240px",
            DrawerWidthRight = "240px",
        },
        Typography = new Typography()
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Inter", "Roboto", "Helvetica", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.43",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography { FontWeight = "300", FontSize = "6rem", LineHeight = "1.167", LetterSpacing = "-.01562em", TextTransform = "none" },
            H2 = new H2Typography { FontWeight = "300", FontSize = "3.75rem", LineHeight = "1.2", LetterSpacing = "-.00833em", TextTransform = "none" },
            H3 = new H3Typography { FontWeight = "400", FontSize = "3rem", LineHeight = "1.167", LetterSpacing = "0", TextTransform = "none" },
            H4 = new H4Typography { FontWeight = "400", FontSize = "2.125rem", LineHeight = "1.235", LetterSpacing = ".00735em", TextTransform = "none" },
            H5 = new H5Typography { FontWeight = "400", FontSize = "1.5rem", LineHeight = "1.334", LetterSpacing = "0", TextTransform = "none" },
            H6 = new H6Typography { FontWeight = "500", FontSize = "1.25rem", LineHeight = "1.6", LetterSpacing = ".0075em", TextTransform = "none" },
            Subtitle1 = new Subtitle1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.75", LetterSpacing = ".00938em", TextTransform = "none" },
            Subtitle2 = new Subtitle2Typography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.57", LetterSpacing = ".00714em", TextTransform = "none" },
            Body1 = new Body1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.5", LetterSpacing = ".00938em", TextTransform = "none" },
            Body2 = new Body2Typography { FontWeight = "400", FontSize = ".875rem", LineHeight = "1.43", LetterSpacing = ".01071em", TextTransform = "none" },
            Button = new ButtonTypography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.75", LetterSpacing = ".02857em", TextTransform = "uppercase" },
            Caption = new CaptionTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "1.66", LetterSpacing = ".03333em", TextTransform = "none" },
            Overline = new OverlineTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "2.66", LetterSpacing = ".08333em", TextTransform = "none" },
        },
        ZIndex = new ZIndex() { AppBar = 1300, Dialog = 1400, Drawer = 1100, Popover = 1200, Snackbar = 1500, Tooltip = 1600 },
    };
}
