/*
 * Pebble — earthy warm-gray theme with a green-teal primary accent.
 * The most subtle background of the bunch — just a hint of warmth.
 */

using MudBlazor;

namespace TD.Themes;

public static class PebbleTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight()
        {
            TableHover = "rgba(0,0,0,0.03)",
            OverlayLight = "rgba(255,255,255,0.5)",
            OverlayDark = "rgba(33,33,33,0.5)",
            GrayDarker = "#616161",
            GrayDark = "#757575",
            GrayLighter = "#E8E5E1",
            GrayLight = "#C8C4BF",
            GrayDefault = "#A3A09B",
            RippleOpacitySecondary = 0.18,
            RippleOpacity = 0.08,
            HoverOpacity = 0.04,
            Surface = "#fefefe",
            Background = "#faf9f7",
            BackgroundGray = "#f3f2f0",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(200,196,191,1)",
            ActionDisabled = "rgba(0,0,0,0.26)",
            TextDisabled = "rgba(0,0,0,0.38)",
            TableStriped = "rgba(0,0,0,0.015)",
            LinesDefault = "rgba(0,0,0,0.09)",
            ActionDisabledBackground = "rgba(0,0,0,0.1)",
            TableLines = "rgba(232,229,225,1)",
            Divider = "rgba(232,229,225,1)",
            DividerLight = "rgba(0,0,0,0.05)",
            Error = "#D32F2F",
            Tertiary = "#A1887F",
            TertiaryLighten = "#BCAAA4",
            TertiaryDarken = "#795548",
            ActionDefault = "rgba(0,0,0,0.54)",
            DarkLighten = "rgb(85,82,78)",
            ErrorLighten = "#EF5350",
            ErrorDarken = "#B71C1C",
            DarkDarken = "rgb(42,40,38)",
            White = "#fff",
            SecondaryLighten = "#f5f4f2",
            WarningDarken = "#E65100",
            PrimaryContrastText = "#ffffff",
            TextPrimary = "#3E4A40",
            TextSecondary = "#6D7B6F",
            TertiaryContrastText = "#ffffff",
            DarkContrastText = "#D7CCC8",
            Secondary = "#EFEBE9",
            DrawerIcon = "#6D7B6F",
            DrawerText = "#3E4A40",
            Warning = "#EF6C00",
            SecondaryDarken = "#D7CCC8",
            InfoDarken = "#00838F",
            SuccessDarken = "#2E7D32",
            Info = "#26C6DA",
            Success = "#66BB6A",
            Dark = "#3E2723",
            DrawerBackground = "#fbfaf8",
            WarningLighten = "#FFE0B2",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#4E342E",
            InfoContrastText = "#E0F7FA",
            InfoLighten = "#E0F7FA",
            SuccessContrastText = "#E8F5E9",
            SuccessLighten = "#E8F5E9",
            PrimaryLighten = "#5EA88A",
            PrimaryDarken = "#2C6E4F",
            Primary = "#3D8B6A",
            AppbarText = "#3E4A40",
            AppbarBackground = "#faf9f7",
            Black = "#000",
        },
        PaletteDark = new PaletteDark()
        {
            Surface = "rgba(50,48,44,1)",
            Background = "rgba(42,40,36,1)",
            BackgroundGray = "rgba(34,32,28,1)",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(255,255,255,0.28)",
            ActionDisabled = "rgba(255,255,255,0.26)",
            TextDisabled = "rgba(255,255,255,0.2)",
            TableStriped = "rgba(255,255,255,0.04)",
            LinesDefault = "rgba(255,255,255,0.1)",
            ActionDisabledBackground = "rgba(255,255,255,0.1)",
            TableLines = "rgba(255,255,255,0.1)",
            Divider = "rgba(255,255,255,0.1)",
            DividerLight = "rgba(255,255,255,0.05)",
            Error = "#EF5350",
            Tertiary = "#BCAAA4",
            TertiaryLighten = "#D7CCC8",
            TertiaryDarken = "#A1887F",
            ActionDefault = "rgba(188,170,164,1)",
            DarkLighten = "rgb(60,58,54)",
            ErrorLighten = "#EF9A9A",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(22,20,18)",
            White = "#fff",
            SecondaryLighten = "#795548",
            WarningDarken = "#FFB74D",
            PrimaryContrastText = "#EFEBE9",
            TextPrimary = "#EFEBE9",
            TextSecondary = "#D7CCC8",
            TertiaryContrastText = "#EFEBE9",
            DarkContrastText = "#EFEBE9",
            Secondary = "#4E342E",
            DrawerIcon = "#D7CCC8",
            DrawerText = "#EFEBE9",
            Warning = "#FFA726",
            SecondaryDarken = "#3E2723",
            InfoDarken = "#80DEEA",
            SuccessDarken = "#A5D6A7",
            Info = "#26C6DA",
            Success = "#66BB6A",
            Dark = "#3E2723",
            DrawerBackground = "#1e1c18",
            WarningLighten = "#3E2723",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#EFEBE9",
            InfoContrastText = "#0A2629",
            InfoLighten = "#0A2629",
            SuccessContrastText = "#0D2E16",
            SuccessLighten = "#0D2E16",
            PrimaryLighten = "#6AB893",
            PrimaryDarken = "#2C6E4F",
            Primary = "#4CAF7A",
            AppbarText = "#D7CCC8",
            AppbarBackground = "#1a1816",
            Black = "#000",
        },
        LayoutProperties = new LayoutProperties()
        {
            AppbarHeight = "64px",
            DefaultBorderRadius = "6px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
            DrawerWidthLeft = "240px",
            DrawerWidthRight = "240px",
        },
        Typography = new Typography()
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.43",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography { FontWeight = "300", FontSize = "6rem", LineHeight = "1.167", LetterSpacing = "-.01562em", TextTransform = "none" },
            H2 = new H2Typography { FontWeight = "300", FontSize = "3.75rem", LineHeight = "1.2", LetterSpacing = "-.00833em", TextTransform = "none" },
            H3 = new H3Typography { FontWeight = "400", FontSize = "3rem", LineHeight = "1.167", LetterSpacing = "0", TextTransform = "none" },
            H4 = new H4Typography { FontWeight = "400", FontSize = "2.125rem", LineHeight = "1.235", LetterSpacing = ".00735em", TextTransform = "none" },
            H5 = new H5Typography { FontWeight = "400", FontSize = "1.5rem", LineHeight = "1.334", LetterSpacing = "0", TextTransform = "none" },
            H6 = new H6Typography { FontWeight = "500", FontSize = "1.25rem", LineHeight = "1.6", LetterSpacing = ".0075em", TextTransform = "none" },
            Subtitle1 = new Subtitle1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.75", LetterSpacing = ".00938em", TextTransform = "none" },
            Subtitle2 = new Subtitle2Typography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.57", LetterSpacing = ".00714em", TextTransform = "none" },
            Body1 = new Body1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.5", LetterSpacing = ".00938em", TextTransform = "none" },
            Body2 = new Body2Typography { FontWeight = "400", FontSize = ".875rem", LineHeight = "1.43", LetterSpacing = ".01071em", TextTransform = "none" },
            Button = new ButtonTypography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.75", LetterSpacing = ".02857em", TextTransform = "uppercase" },
            Caption = new CaptionTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "1.66", LetterSpacing = ".03333em", TextTransform = "none" },
            Overline = new OverlineTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "2.66", LetterSpacing = ".08333em", TextTransform = "none" },
        },
        ZIndex = new ZIndex() { AppBar = 1300, Dialog = 1400, Drawer = 1100, Popover = 1200, Snackbar = 1500, Tooltip = 1600 },
    };
}
