/*
 * Silver Linen — warm neutral grays with a barely-there off-white background.
 * Soft, understated, and easy on the eyes. Slate-blue primary accent.
 */

using MudBlazor;

namespace TD.Themes;

public static class SilverLinenTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight()
        {
            TableHover = "rgba(0,0,0,0.03)",
            OverlayLight = "rgba(255,255,255,0.5)",
            OverlayDark = "rgba(33,33,33,0.5)",
            GrayDarker = "#5A5A5A",
            GrayDark = "#757575",
            GrayLighter = "#E8E8E8",
            GrayLight = "#C9C9C9",
            GrayDefault = "#A0A0A0",
            RippleOpacitySecondary = 0.18,
            RippleOpacity = 0.08,
            HoverOpacity = 0.04,
            Surface = "#ffffff",
            Background = "#f9f9f9",
            BackgroundGray = "#f3f3f4",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(200,200,200,1)",
            ActionDisabled = "rgba(0,0,0,0.26)",
            TextDisabled = "rgba(0,0,0,0.38)",
            TableStriped = "rgba(0,0,0,0.015)",
            LinesDefault = "rgba(0,0,0,0.09)",
            ActionDisabledBackground = "rgba(0,0,0,0.1)",
            TableLines = "rgba(232,232,232,1)",
            Divider = "rgba(232,232,232,1)",
            DividerLight = "rgba(0,0,0,0.05)",
            Error = "#D32F2F",
            Tertiary = "#8D99AE",
            TertiaryLighten = "#B8C1CC",
            TertiaryDarken = "#5C6B7A",
            ActionDefault = "rgba(0,0,0,0.54)",
            DarkLighten = "rgb(90,90,90)",
            ErrorLighten = "#EF5350",
            ErrorDarken = "#B71C1C",
            DarkDarken = "rgb(42,42,42)",
            White = "#fff",
            SecondaryLighten = "#f0f0f0",
            WarningDarken = "#E65100",
            PrimaryContrastText = "#ffffff",
            TextPrimary = "#2B2D42",
            TextSecondary = "#6B6E7B",
            TertiaryContrastText = "#ffffff",
            DarkContrastText = "#D6D6D6",
            Secondary = "#EDF2F4",
            DrawerIcon = "#6B6E7B",
            DrawerText = "#3D3F50",
            Warning = "#FB8C00",
            SecondaryDarken = "#D5DADC",
            InfoDarken = "#01579B",
            SuccessDarken = "#1B5E20",
            Info = "#039BE5",
            Success = "#43A047",
            Dark = "#2B2D42",
            DrawerBackground = "#fafafa",
            WarningLighten = "#FFE0B2",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#3D3F50",
            InfoContrastText = "#E1F5FE",
            InfoLighten = "#E1F5FE",
            SuccessContrastText = "#E8F5E9",
            SuccessLighten = "#E8F5E9",
            PrimaryLighten = "#6E7FAE",
            PrimaryDarken = "#1A1B30",
            Primary = "#4A5187",
            AppbarText = "#2B2D42",
            AppbarBackground = "#f9f9f9",
            Black = "#000",
        },
        PaletteDark = new PaletteDark()
        {
            Surface = "rgba(48,48,56,1)",
            Background = "rgba(40,40,48,1)",
            BackgroundGray = "rgba(32,32,40,1)",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(255,255,255,0.28)",
            ActionDisabled = "rgba(255,255,255,0.26)",
            TextDisabled = "rgba(255,255,255,0.2)",
            TableStriped = "rgba(255,255,255,0.04)",
            LinesDefault = "rgba(255,255,255,0.1)",
            ActionDisabledBackground = "rgba(255,255,255,0.1)",
            TableLines = "rgba(255,255,255,0.1)",
            Divider = "rgba(255,255,255,0.1)",
            DividerLight = "rgba(255,255,255,0.05)",
            Error = "#EF5350",
            Tertiary = "#8D99AE",
            TertiaryLighten = "#B8C1CC",
            TertiaryDarken = "#5C6B7A",
            ActionDefault = "rgba(180,180,188,1)",
            DarkLighten = "rgb(58,58,66)",
            ErrorLighten = "#EF9A9A",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(22,22,28)",
            White = "#fff",
            SecondaryLighten = "#5C6B7A",
            WarningDarken = "#FFB74D",
            PrimaryContrastText = "#EDF2F4",
            TextPrimary = "#EDF2F4",
            TextSecondary = "#B8C1CC",
            TertiaryContrastText = "#EDF2F4",
            DarkContrastText = "#EDF2F4",
            Secondary = "#3D3F50",
            DrawerIcon = "#B8C1CC",
            DrawerText = "#D6D6D6",
            Warning = "#FFA726",
            SecondaryDarken = "#2B2D42",
            InfoDarken = "#81D4FA",
            SuccessDarken = "#A5D6A7",
            Info = "#039BE5",
            Success = "#43A047",
            Dark = "#2B2D42",
            DrawerBackground = "#1e1e26",
            WarningLighten = "#3E2723",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#D6D6D6",
            InfoContrastText = "#0A1929",
            InfoLighten = "#0A1929",
            SuccessContrastText = "#0D2E16",
            SuccessLighten = "#0D2E16",
            PrimaryLighten = "#7A8BBE",
            PrimaryDarken = "#2E3460",
            Primary = "#5B64A0",
            AppbarText = "#D6D6D6",
            AppbarBackground = "#1a1a22",
            Black = "#000",
        },
        LayoutProperties = new LayoutProperties()
        {
            AppbarHeight = "64px",
            DefaultBorderRadius = "4px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
            DrawerWidthLeft = "240px",
            DrawerWidthRight = "240px",
        },
        Typography = new Typography()
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.43",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography { FontWeight = "300", FontSize = "6rem", LineHeight = "1.167", LetterSpacing = "-.01562em", TextTransform = "none" },
            H2 = new H2Typography { FontWeight = "300", FontSize = "3.75rem", LineHeight = "1.2", LetterSpacing = "-.00833em", TextTransform = "none" },
            H3 = new H3Typography { FontWeight = "400", FontSize = "3rem", LineHeight = "1.167", LetterSpacing = "0", TextTransform = "none" },
            H4 = new H4Typography { FontWeight = "400", FontSize = "2.125rem", LineHeight = "1.235", LetterSpacing = ".00735em", TextTransform = "none" },
            H5 = new H5Typography { FontWeight = "400", FontSize = "1.5rem", LineHeight = "1.334", LetterSpacing = "0", TextTransform = "none" },
            H6 = new H6Typography { FontWeight = "500", FontSize = "1.25rem", LineHeight = "1.6", LetterSpacing = ".0075em", TextTransform = "none" },
            Subtitle1 = new Subtitle1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.75", LetterSpacing = ".00938em", TextTransform = "none" },
            Subtitle2 = new Subtitle2Typography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.57", LetterSpacing = ".00714em", TextTransform = "none" },
            Body1 = new Body1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.5", LetterSpacing = ".00938em", TextTransform = "none" },
            Body2 = new Body2Typography { FontWeight = "400", FontSize = ".875rem", LineHeight = "1.43", LetterSpacing = ".01071em", TextTransform = "none" },
            Button = new ButtonTypography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.75", LetterSpacing = ".02857em", TextTransform = "uppercase" },
            Caption = new CaptionTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "1.66", LetterSpacing = ".03333em", TextTransform = "none" },
            Overline = new OverlineTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "2.66", LetterSpacing = ".08333em", TextTransform = "none" },
        },
        ZIndex = new ZIndex() { AppBar = 1300, Dialog = 1400, Drawer = 1100, Popover = 1200, Snackbar = 1500, Tooltip = 1600 },
    };
}
