/*
 * TouchDown — the brand theme. Gridiron-orange primary (#ff7a45, the locked TouchDown
 * mark accent) over Frost's clean neutral canvas.
 */

using MudBlazor;

namespace TD.Themes;

public static class TouchDownTheme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight()
        {
            TableHover = "rgba(0,0,0,0.035)",
            OverlayLight = "rgba(255,255,255,0.5)",
            OverlayDark = "rgba(33,33,33,0.5)",
            GrayDarker = "#546E7A",
            GrayDark = "#78909C",
            GrayLighter = "#ECEFF1",
            GrayLight = "#CFD8DC",
            GrayDefault = "#B0BEC5",
            RippleOpacitySecondary = 0.2,
            RippleOpacity = 0.1,
            HoverOpacity = 0.04,
            Surface = "#ffffff",
            Background = "#f8f9fa",
            BackgroundGray = "#f1f3f5",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(176,190,197,1)",
            ActionDisabled = "rgba(0,0,0,0.26)",
            TextDisabled = "rgba(0,0,0,0.38)",
            TableStriped = "rgba(0,0,0,0.018)",
            LinesDefault = "rgba(0,0,0,0.1)",
            ActionDisabledBackground = "rgba(0,0,0,0.12)",
            TableLines = "rgba(236,239,241,1)",
            Divider = "rgba(236,239,241,1)",
            DividerLight = "rgba(0,0,0,0.06)",
            Error = "#E53935",
            Tertiary = "#78909C",
            TertiaryLighten = "#B0BEC5",
            TertiaryDarken = "#546E7A",
            ActionDefault = "rgba(0,0,0,0.54)",
            DarkLighten = "rgb(84,110,122)",
            ErrorLighten = "#EF5350",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(38,50,56)",
            White = "#fff",
            SecondaryLighten = "#f5f5f5",
            WarningDarken = "#E65100",
            PrimaryContrastText = "#ffffff",
            TextPrimary = "#37474F",
            TextSecondary = "#607D8B",
            TertiaryContrastText = "#ffffff",
            DarkContrastText = "#CFD8DC",
            Secondary = "#ECEFF1",
            DrawerIcon = "#607D8B",
            DrawerText = "#455A64",
            Warning = "#FF9800",
            SecondaryDarken = "#CFD8DC",
            InfoDarken = "#0277BD",
            SuccessDarken = "#2E7D32",
            Info = "#29B6F6",
            Success = "#66BB6A",
            Dark = "#263238",
            DrawerBackground = "#fafbfc",
            WarningLighten = "#FFE0B2",
            WarningContrastText = "#4E342E",
            SecondaryContrastText = "#455A64",
            InfoContrastText = "#E1F5FE",
            InfoLighten = "#E1F5FE",
            SuccessContrastText = "#E8F5E9",
            SuccessLighten = "#E8F5E9",
            PrimaryLighten = "#ff9a6b",
            PrimaryDarken = "#b5451a",
            Primary = "#ff7a45",
            AppbarText = "#37474F",
            AppbarBackground = "#f8f9fa",
            Black = "#000",
        },
        PaletteDark = new PaletteDark()
        {
            Surface = "rgba(46,52,58,1)",
            Background = "rgba(38,44,50,1)",
            BackgroundGray = "rgba(30,36,42,1)",
            ErrorContrastText = "#ffffff",
            LinesInputs = "rgba(255,255,255,0.3)",
            ActionDisabled = "rgba(255,255,255,0.26)",
            TextDisabled = "rgba(255,255,255,0.2)",
            TableStriped = "rgba(255,255,255,0.04)",
            LinesDefault = "rgba(255,255,255,0.12)",
            ActionDisabledBackground = "rgba(255,255,255,0.12)",
            TableLines = "rgba(255,255,255,0.12)",
            Divider = "rgba(255,255,255,0.12)",
            DividerLight = "rgba(255,255,255,0.06)",
            Error = "#EF5350",
            Tertiary = "#90A4AE",
            TertiaryLighten = "#B0BEC5",
            TertiaryDarken = "#78909C",
            ActionDefault = "rgba(176,190,197,1)",
            DarkLighten = "rgb(46,52,58)",
            ErrorLighten = "#EF9A9A",
            ErrorDarken = "#C62828",
            DarkDarken = "rgb(20,24,28)",
            White = "#fff",
            SecondaryLighten = "#546E7A",
            WarningDarken = "#FFB74D",
            PrimaryContrastText = "#FFF3ED",
            TextPrimary = "#ECEFF1",
            TextSecondary = "#B0BEC5",
            TertiaryContrastText = "#ECEFF1",
            DarkContrastText = "#ECEFF1",
            Secondary = "#455A64",
            DrawerIcon = "#B0BEC5",
            DrawerText = "#CFD8DC",
            Warning = "#FFA726",
            SecondaryDarken = "#37474F",
            InfoDarken = "#81D4FA",
            SuccessDarken = "#A5D6A7",
            Info = "#29B6F6",
            Success = "#66BB6A",
            Dark = "#263238",
            DrawerBackground = "#1e242a",
            WarningLighten = "#3E2723",
            WarningContrastText = "#3E2723",
            SecondaryContrastText = "#CFD8DC",
            InfoContrastText = "#0D2137",
            InfoLighten = "#0D2137",
            SuccessContrastText = "#0D2E16",
            SuccessLighten = "#0D2E16",
            PrimaryLighten = "#ff9a6b",
            PrimaryDarken = "#b5451a",
            Primary = "#ff7a45",
            AppbarText = "#CFD8DC",
            AppbarBackground = "#1a2026",
            Black = "#000",
        },
        LayoutProperties = new LayoutProperties()
        {
            AppbarHeight = "64px",
            DefaultBorderRadius = "6px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
            DrawerWidthLeft = "240px",
            DrawerWidthRight = "240px",
        },
        Typography = new Typography()
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Inter", "Roboto", "Helvetica", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.43",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography { FontWeight = "300", FontSize = "6rem", LineHeight = "1.167", LetterSpacing = "-.01562em", TextTransform = "none" },
            H2 = new H2Typography { FontWeight = "300", FontSize = "3.75rem", LineHeight = "1.2", LetterSpacing = "-.00833em", TextTransform = "none" },
            H3 = new H3Typography { FontWeight = "400", FontSize = "3rem", LineHeight = "1.167", LetterSpacing = "0", TextTransform = "none" },
            H4 = new H4Typography { FontWeight = "400", FontSize = "2.125rem", LineHeight = "1.235", LetterSpacing = ".00735em", TextTransform = "none" },
            H5 = new H5Typography { FontWeight = "400", FontSize = "1.5rem", LineHeight = "1.334", LetterSpacing = "0", TextTransform = "none" },
            H6 = new H6Typography { FontWeight = "500", FontSize = "1.25rem", LineHeight = "1.6", LetterSpacing = ".0075em", TextTransform = "none" },
            Subtitle1 = new Subtitle1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.75", LetterSpacing = ".00938em", TextTransform = "none" },
            Subtitle2 = new Subtitle2Typography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.57", LetterSpacing = ".00714em", TextTransform = "none" },
            Body1 = new Body1Typography { FontWeight = "400", FontSize = "1rem", LineHeight = "1.5", LetterSpacing = ".00938em", TextTransform = "none" },
            Body2 = new Body2Typography { FontWeight = "400", FontSize = ".875rem", LineHeight = "1.43", LetterSpacing = ".01071em", TextTransform = "none" },
            Button = new ButtonTypography { FontWeight = "500", FontSize = ".875rem", LineHeight = "1.75", LetterSpacing = ".02857em", TextTransform = "uppercase" },
            Caption = new CaptionTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "1.66", LetterSpacing = ".03333em", TextTransform = "none" },
            Overline = new OverlineTypography { FontWeight = "400", FontSize = ".75rem", LineHeight = "2.66", LetterSpacing = ".08333em", TextTransform = "none" },
        },
        ZIndex = new ZIndex() { AppBar = 1300, Dialog = 1400, Drawer = 1100, Popover = 1200, Snackbar = 1500, Tooltip = 1600 },
    };
}
